# Assignment B2

## Loading the dataset

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("air_quality.csv")

In [3]:
df

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category
0,Russian Federation,Praskoveya,51,Moderate,1,Good,36,Good,0,Good,51,Moderate
1,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good
2,Italy,Priolo Gargallo,66,Moderate,1,Good,39,Good,2,Good,66,Moderate
3,Poland,Przasnysz,34,Good,1,Good,34,Good,0,Good,20,Good
4,France,Punaauia,22,Good,0,Good,22,Good,0,Good,6,Good
...,...,...,...,...,...,...,...,...,...,...,...,...
23458,India,Gursahaiganj,184,Unhealthy,3,Good,154,Unhealthy,2,Good,184,Unhealthy
23459,France,Sceaux,50,Good,1,Good,20,Good,5,Good,50,Good
23460,India,Mormugao,50,Good,1,Good,22,Good,1,Good,50,Good
23461,United States of America,Westerville,71,Moderate,1,Good,44,Good,2,Good,71,Moderate
23462,Malaysia,Marang,70,Moderate,1,Good,38,Good,0,Good,70,Moderate

## Data cleaning

In [4]:
df.fillna(method="ffill",inplace=True)

C:\Users\sheik\AppData\Local\Temp\ipykernel_17972\1844562654.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill",inplace=True)

In [5]:
df

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category
0,Russian Federation,Praskoveya,51,Moderate,1,Good,36,Good,0,Good,51,Moderate
1,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good
2,Italy,Priolo Gargallo,66,Moderate,1,Good,39,Good,2,Good,66,Moderate
3,Poland,Przasnysz,34,Good,1,Good,34,Good,0,Good,20,Good
4,France,Punaauia,22,Good,0,Good,22,Good,0,Good,6,Good
...,...,...,...,...,...,...,...,...,...,...,...,...
23458,India,Gursahaiganj,184,Unhealthy,3,Good,154,Unhealthy,2,Good,184,Unhealthy
23459,France,Sceaux,50,Good,1,Good,20,Good,5,Good,50,Good
23460,India,Mormugao,50,Good,1,Good,22,Good,1,Good,50,Good
23461,United States of America,Westerville,71,Moderate,1,Good,44,Good,2,Good,71,Moderate
23462,Malaysia,Marang,70,Moderate,1,Good,38,Good,0,Good,70,Moderate

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category
0,Russian Federation,Praskoveya,51,Moderate,1,Good,36,Good,0,Good,51,Moderate
1,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good
2,Italy,Priolo Gargallo,66,Moderate,1,Good,39,Good,2,Good,66,Moderate
3,Poland,Przasnysz,34,Good,1,Good,34,Good,0,Good,20,Good
4,France,Punaauia,22,Good,0,Good,22,Good,0,Good,6,Good
...,...,...,...,...,...,...,...,...,...,...,...,...
23458,India,Gursahaiganj,184,Unhealthy,3,Good,154,Unhealthy,2,Good,184,Unhealthy
23459,France,Sceaux,50,Good,1,Good,20,Good,5,Good,50,Good
23460,India,Mormugao,50,Good,1,Good,22,Good,1,Good,50,Good
23461,United States of America,Westerville,71,Moderate,1,Good,44,Good,2,Good,71,Moderate
23462,Malaysia,Marang,70,Moderate,1,Good,38,Good,0,Good,70,Moderate

## Data integration

In [8]:
data1=["Country","City","AQI Value","AQI Category","CO AQI Value"]
data2=["Ozone AQI Value","Ozone AQI Category","NO2 AQI Value","NO2 AQI Category","PM2.5 AQI Value","PM2.5 AQI Category"]

In [9]:
part1=df[data1]
part2=df[data2]

In [10]:
part1

,Country,City,AQI Value,AQI Category,CO AQI Value
0,Russian Federation,Praskoveya,51,Moderate,1
1,Brazil,Presidente Dutra,41,Good,1
2,Italy,Priolo Gargallo,66,Moderate,1
3,Poland,Przasnysz,34,Good,1
4,France,Punaauia,22,Good,0
...,...,...,...,...,...
23458,India,Gursahaiganj,184,Unhealthy,3
23459,France,Sceaux,50,Good,1
23460,India,Mormugao,50,Good,1
23461,United States of America,Westerville,71,Moderate,1
23462,Malaysia,Marang,70,Moderate,1

In [11]:
part2

,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category
0,36,Good,0,Good,51,Moderate
1,5,Good,1,Good,41,Good
2,39,Good,2,Good,66,Moderate
3,34,Good,0,Good,20,Good
4,22,Good,0,Good,6,Good
...,...,...,...,...,...,...
23458,154,Unhealthy,2,Good,184,Unhealthy
23459,20,Good,5,Good,50,Good
23460,22,Good,1,Good,50,Good
23461,44,Good,2,Good,71,Moderate
23462,38,Good,0,Good,70,Moderate

In [12]:
merge_df=pd.concat([part1,part2],axis=1)

In [13]:
merge_df

,Country,City,AQI Value,AQI Category,CO AQI Value,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category
0,Russian Federation,Praskoveya,51,Moderate,1,36,Good,0,Good,51,Moderate
1,Brazil,Presidente Dutra,41,Good,1,5,Good,1,Good,41,Good
2,Italy,Priolo Gargallo,66,Moderate,1,39,Good,2,Good,66,Moderate
3,Poland,Przasnysz,34,Good,1,34,Good,0,Good,20,Good
4,France,Punaauia,22,Good,0,22,Good,0,Good,6,Good
...,...,...,...,...,...,...,...,...,...,...,...
23458,India,Gursahaiganj,184,Unhealthy,3,154,Unhealthy,2,Good,184,Unhealthy
23459,France,Sceaux,50,Good,1,20,Good,5,Good,50,Good
23460,India,Mormugao,50,Good,1,22,Good,1,Good,50,Good
23461,United States of America,Westerville,71,Moderate,1,44,Good,2,Good,71,Moderate
23462,Malaysia,Marang,70,Moderate,1,38,Good,0,Good,70,Moderate

In [15]:
# ERROR CORRECTION

# Calculate the 99th percentile of AQI values
import numpy as np
percentile_99 = np.percentile(merge_df['AQI Value'], 99)

# Define the threshold for outliers
threshold = percentile_99

# Calculate the mean and standard deviation of AQI values
mean_aqi = merge_df['AQI Value'].mean()
std_aqi = merge_df['AQI Value'].std()

# Identify outliers using the threshold
lower_bound = mean_aqi - threshold * std_aqi
upper_bound = mean_aqi + threshold * std_aqi

# Remove outliers from the dataset
merge_df = merge_df[(merge_df['AQI Value'] >= lower_bound) & (merge_df['AQI Value'] <= upper_bound)]

print("Outliers removed.")

Outliers removed.

## Data transformation

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler=StandardScaler()
scaled_features=scaler.fit_transform(merge_df[['AQI Value','Ozone AQI Value']])

In [18]:
scaled_features

array([[-0.37483246,  0.02869554],
       [-0.55323178, -1.07458094],
       [-0.10723348,  0.13546423],
       ...,
       [-0.39267239, -0.46955836],
       [-0.01803382,  0.31341205],
       [-0.03587375,  0.09987466]])

## Data model

In [19]:
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.linear_model import LogisticRegression

In [20]:
X=merge_df['AQI Value']
Y=merge_df['CO AQI Value']

In [21]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=40)

In [22]:
X_train_reshaped = X_train.values.reshape(-1, 1)  
Y_train_reshaped = Y_train.values.reshape(-1, 1)

In [23]:
model=LogisticRegression()
model.fit(X_train_reshaped,Y_train_reshaped)

G:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
G:\Anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()